sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
after_script:
  # kill phantomjs that's running in the background
  - ps -A | grep -i phantomj[s] | grep -oP '^([ ])*\K([0-9])+' | xargs kill -9
before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/7.10.2/bin:$PATH
before_script:
  # Change node version
  - nvm install 5.4.0
  # Update phantom js to 2.0.0
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-14.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-14.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-14.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - phantomjs --version
  # Add database tables
  - psql -c 'create database website;' -U postgres
  - psql -c 'create database website_test;' -U postgres
  - npm install
  - npm run compile-less
  # Run phantomjs in the background
  - (phantomjs --webdriver=4444 > /dev/null & ) || /bin/true
  - stack install yesod-bin cabal-install --install-ghc
  - stack install
  # Run the built binary in the background
  - (website > /dev/null & ) || /bin/true
  - sleep 5
# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
env:
  - PGUSER="postgres" PGPASS=""
script:
  - stack --no-terminal --skip-ghc-check test
  - npm run test
services:
  - postgresql
