name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node-version: [14.17.1]
        operating-system: [ 'ubuntu-20.04' ]
    steps:
    - name: Install phatom js
      run: |
        mkdir travis-phantomjs
        wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-20.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-20.04.tar.bz2
        tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-20.04.tar.bz2 -C $PWD/travis-phantomjs
        export PATH=$PWD/travis-phantomjs:$PATH
        phantomjs --version
#   lint:
#     runs-on: ${{ matrix.operating-system }}
#     strategy:
#       matrix:
#         node-version: [14.17.1]
#         operating-system: [ 'ubuntu-20.04' ]
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: npm install
#       run: npm ci
#     - name: npm run lint
#       run: npm run lint
  build:
    needs: setup
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node-version: [14.17.1]
        operating-system: [ 'ubuntu-20.04' ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: npm run build
      run: npm run build
  test:
    needs: setup
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node-version: [14.17.1]
        operating-system: [ 'ubuntu-20.04' ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: npm run test
      run: npm run test
