name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node-version: [16]
        operating-system: [ 'ubuntu-20.04' ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: node version
      run: node --version
    - name: npm version
      run: npm --version
    - name: Install phatom js
      run: npm install phantomjs-prebuilt
    - name: Run phantom js in background
      run: npm exec -- phantomjs --webdriver=4444 &
    - name: npm install
      run: npm ci
    - name: npm run test
      run: npm run test
#   lint:
#     runs-on: ${{ matrix.operating-system }}
#     strategy:
#       matrix:
#         node-version: [16]
#         operating-system: [ 'ubuntu-20.04' ]
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: npm install
#       run: npm ci
#     - name: npm run lint
#       run: npm run lint
#   build:
#     needs: setup
#     runs-on: ${{ matrix.operating-system }}
#     strategy:
#       matrix:
#         node-version: [16]
#         operating-system: [ 'ubuntu-20.04' ]
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: npm install
#       run: npm ci
#     - name: npm run build
#       run: npm run build
